# Generated by Django 4.0.4 on 2022-04-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='tags',
            field=models.CharField(choices=[('created', 'Created'), ('progress', 'In Progress'), ('done', 'Done')], default='C', max_length=100),
        ),
    ]
